name: ytquran
description: A new Flutter project.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.19.0-120.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.13
  scrollable_positioned_list: ^0.2.3
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.15
  
  


    
  
  flutter_local_notifications: ^9.6.1
  sound_mode: ^2.0.2
  provider: ^6.0.2
  intl: ^0.17.0
  introduction_screen: ^3.0.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.0.3
  share_plus: ^4.0.10
  android_alarm_manager_plus: ^2.0.6
  clear_all_notifications: ^0.0.3


    
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/quran.png
  android: true
  ios: true
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: quran
      fonts:
        - asset: assets/HafsSmart_08.ttf
    - family: me_quran
      fonts:
        - asset: assets/me_quran.ttf
