import 'package:flutter/material.dart';

class Names extends StatelessWidget {
  final List<String> namesOfAllah = [
    'Ar-Rahman', 
    'Ar-Rahim', 
    'Al-Malik', 
    'Al-Quddus', 
    'As-Salam', 
    'Al-MuMin', 
    'Al-Muhaymin', 
    'Al-Aziz', 
    'Al-Jabbar',
    'Al-Mutakabbir',
    'Al-Khaliq',
    'Al-Bari',
    'Al-Musawwir',
    'Al-Ghaffar',
    'Al-Qahhar',
    'Al-Wahhab',
    'Ar-Razzaq',
    'Al-Fattah',
    'Al-Alim',
    'Al-Qabid',
    'Al-Basit',
    'Al-Khafid',
    'Ar-Rafi',
    'Al-Muizz',
    'Al-Mudhill',
    'As-Sami',
    'Al-Basir',
    'Al-Hakam',
    'Al-Adl',
    'Al-Latif',
    'Al-Khabir',
    'Al-Halim',
    'Al-Azim',
    'Al-Ghafur',
    'Ash-Shakur',
    'Al-Ali',
    'Al-Kabir',
    'Al-Hafiz',
    'Al-Muqit',
    'Al-Hasib',
    'Al-Jalil',
    'Al-Karim',
    'Ar-Raqib',
    'Al-Mujib',
    'Al-Wasi',
    'Al-Hakim',
    'Al-Wadud',
    'Al-Majid',
    'Al-BaIth',
    'Ash-Shahid',
    'Al-Haqq',
    'Al-Wakil',
    'Al-Qawi',
    'Al-Matin',
    'Al-Wali',
    'Al-Hamid',
    'Al-Muhsi',
    'Al-Mubdi',
    'Al-MuId',
    'Al-Muhyi',
    'Al-Mumit',
    'Al-Hayy',
    'Al-Qayyum',
    'Al-Wajid',
    'Al-Majid',
    'Al-Wahid',
    'Al-Ahad',
    'As-Samad',
    'Al-Qadir',
    'Al-Muqtadir',
    'Al-Muqaddim',
    'Al-MuAkhkhir',
    'Al-Awwal',
    'Al-Akhir',
    'Az-Zahir',
    'Al-Batin',
    'Al-Wali',
    'Al-MutaAli',
    'Al-Barr',
    'At-Tawwab',
    'Al-Muntaqim',
    'Al-Afu',
    'Ar-RaUf',
    'Malik Al-Mulk',
    'Thul-Jalali Wal-Ikram',
    'Al-Muqsit',
    'Al-Jami',
    'Al-Ghani',
    'Al-Mughni',
    'Al-Mani',
    'Ad-Darr',
    'An-Nafi',
    'An-Nur',
    'Al-Hadi',
    'Al-Badi',
    'Al-Baqi',
    'Al-Warith',
    'Ar-Rashid',
    'As-Sabur',
  ];

   @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('99 Names of Allah'),
      ),
      body: GridView.builder(
        padding: EdgeInsets.all(10),
        itemCount: namesOfAllah.length,
        gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
          crossAxisCount: 3,
          crossAxisSpacing: 10,
          mainAxisSpacing: 10,
        ),
        itemBuilder: (BuildContext context, int index) {
          return Container(
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(
                  color: Colors.grey.withOpacity(0.5),
                  spreadRadius: 2,
                  blurRadius: 5,
                  offset: Offset(0, 3),
                ),
              ],
            ),
            child: Center(
              child: Text(
                namesOfAllah[index],
                textAlign: TextAlign.center,
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
          );
        },
      ),
    );
  }
}